
name: packaging-actions
run-name: ${{ github.actor }} is packaging
on: [push]
jobs:
  item-folder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python scripts/make_item_folder.py
      - name: commit results
        run: |
         git config --global user.email "actions@example.com"
         git config --global user.name "Github Actions"
         git checkout -b packages
         mv build/* ./
         git status
         git add packages/.
         git commit -m "CI packaging"
         git status
         git push

      # - name: Commit packages
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     #committer_name: GitHub Actions
      #     #committer_email: actions@github.com
      #     message: 'CI packaging'
      #     new_branch: packages
      #     #pull: '--rebase --autostash ...'
      #     #cwd: './build'
      #     add: 'packages/. --force'
