
name: packaging-actions
run-name: ${{ github.actor }} is packaging
on: [push]
jobs:
  item-folder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
         python scripts/make_item_folder.py

      - name: Commit packages
        uses: EndBug/add-and-commit@v9
        with:
          #committer_name: GitHub Actions
          #committer_email: actions@github.com
          message: 'CI packaging'
          new_branch: packages
          cwd: './build'
          add: '. --force'
