
name: packaging-actions
run-name: ${{ github.actor }} is packaging
on: [push]
jobs:
  item-folder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python scripts/make_item_folder.py
      - name: commit results
        run: |
         git config --global user.email "lindemann09@users.noreply.github.com'"
         git config --global user.name "Github Actions"
         git checkout -b packages
         git push --set-upstream origin packages
         mv build/* ./
         git add packages/.
         git commit -am "CI packaging"
         git push

      # - name: Commit packages
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     #committer_name: GitHub Actions
      #     #committer_email: actions@github.com
      #     message: 'CI packaging'
      #     new_branch: packages
      #     #pull: '--rebase --autostash ...'
      #     #cwd: './build'
      #     add: 'packages/. --force'

  pushdemo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
