
name: packaging-actions
run-name: ${{ github.actor }} is packaging
on: [push]
jobs:
  # item-folder:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.10'
  #     - run: python scripts/make_item_folder.py
  #     - name: commit results
  #       run: |
  #        git config user.email "lindemann09@users.noreply.github.com'"
  #        git config user.name "Github Actions"
  #        git checkout -b packages
  #        git push --set-upstream origin packages
  #        mv build/* ./
  #        git add packages/.
  #        git commit -m "CI packaging"
  #        git push

  pushdemo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Commit
        run: |
          git config user.email "lindemann09@users.noreply.github.com'"
          git config user.name "Github Actions"
          git checkout -b packages
          date > generated.txt
          git add generated.txt
          git commit -m "CI commit"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}