
name: packaging-actions
run-name: ${{ github.actor }} is packaging
on:
  push:
    branches:
      - main
jobs:
  item-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        uses: Rscript -e 'source("scripts/install_requirements.R")'

      - name: Install git restore timestamps
        run: |
          sudo apt install git-restore-mtime

      - uses: actions/checkout@v3
      - name: set up git
        run: |
          git config user.email "lindemann09@users.noreply.github.com'"
          git config user.name "Github Actions"
          git restore-mtime

      - name: Make tarballs
        run: python scripts/make_item_folder.py

      - name: commit results
        run: |
          git fetch origin packages
          git checkout packages
          rm packages -rf
          mv build packages
          sha1sum packages/tarballs/* > checksums.txt
          git add packages/.
          git add checksums.txt
          git commit -m "CI packaging"
          git push --set-upstream origin packages --force
