
name: packaging-actions
run-name: ${{ github.actor }} is packaging
on:
  push:
    branches:
      - main
jobs:
  item-folder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Restore Timestamps
        uses: chetan/git-restore-mtime-action@v1
      - run: |
          python scripts/make_item_folder.py

      - name: set up git
        run: |
          git config user.email "lindemann09@users.noreply.github.com'"
          git config user.name "Github Actions"

      - name: commit results
        run: |
          git fetch origin packages
          git checkout packages
          rm packages -rf
          mv build packages
          sha1sum packages/tarballs/* > checksums.txt
          git add packages/.
          git add checksums.txt
          git commit -m "CI packaging"
          git push --set-upstream origin packages --force